[package]
name = "fin-stat"
description = "An application for tracking your finances."
version = "0.1.0"
authors = ["David Lawrence Campbell"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["finance"]
categories = ["finance"]
homepage = "https://github.com/dcampbell24/fin-stat"
# documentation = "https://docs.rs/fin-stat"
repository = "https://github.com/dcampbell24/fin-stat"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
iced = "0.10"
regex = "1"
rust_decimal = "1"
rust_decimal_macros = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thousands = "0.2"

[package.metadata.deb]
assets = [
    ["target/release/fin-stat", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/fin-stat/README.md", "644"],
    ["fin-stat.desktop", "usr/share/applications/", "644"],
    ["icons/fin-stat_16x16.png", "usr/share/icons/hicolor/16x16/apps/fin-stat.png", "644"],
    ["icons/fin-stat_32x32.png", "usr/share/icons/hicolor/32x32/apps/fin-stat.png", "644"],
    ["icons/fin-stat_64x64.png", "usr/share/icons/hicolor/64x64/apps/fin-stat.png", "644"],
    ["icons/fin-stat_128x128.png", "usr/share/icons/hicolor/128x128/apps/fin-stat.png", "644"],
]
