[package]
name = "fin-stat"
description = "An application for tracking your finances."
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["finance"]
categories = ["finance"]
homepage = "https://github.com/dcampbell24/fin-stat"
# documentation = "https://docs.rs/fin-stat"
repository = "https://github.com/dcampbell24/fin-stat"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
iced = "0.10.0"
rust_decimal = "1.29.1"
rust_decimal_macros = "1.29.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thousands = "0.2.0"
