[package]
name = "fin-stat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
rust_decimal = "1.29.1"
rust_decimal_macros = "1.29.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thousands = "0.2.0"
