[package]
name = "fin-stat"
description = "Application for tracking your finances."
version = "0.2.0-dev"
authors = ["David Lawrence Campbell"]
edition = "2021"
license-file = "LICENSE.txt"
keywords = ["finance"]
categories = ["finance"]
homepage = "https://github.com/dcampbell24/fin-stat"
documentation = "https://docs.rs/fin-stat"
repository = "https://github.com/dcampbell24/fin-stat"
readme = "README.md"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
clap_lex = "0.7"
csv = "1"
iced = "0.12"
regex = "1"
rust_decimal = "1"
rust_decimal_macros = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thousands = "0.2"

[package.metadata.deb]
maintainer = "David Campbell <dcampbell24@gmail.com>"
assets = [
    ["target/release/fin-stat", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/fin-stat/", "644"],
    ["fin-stat.1.gz", "usr/share/man/man1/", "644"],
    ["fin-stat.desktop", "usr/share/applications/", "644"],
    ["icons/fin-stat_16x16.png", "usr/share/icons/hicolor/16x16/apps/fin-stat.png", "644"],
    ["icons/fin-stat_22x22.png", "usr/share/icons/hicolor/22x22/apps/fin-stat.png", "644"],
    ["icons/fin-stat_24x24.png", "usr/share/icons/hicolor/24x24/apps/fin-stat.png", "644"],
    ["icons/fin-stat_32x32.png", "usr/share/icons/hicolor/32x32/apps/fin-stat.png", "644"],
    ["icons/fin-stat_42x42.png", "usr/share/icons/hicolor/42x42/apps/fin-stat.png", "644"],
    ["icons/fin-stat_64x64.png", "usr/share/icons/hicolor/64x64/apps/fin-stat.png", "644"],
    ["icons/fin-stat_128x128.png", "usr/share/icons/hicolor/128x128/apps/fin-stat.png", "644"],
]
changelog = "changelog.Debian"
section = "misc"
